version: "3.9"
services:
  envoy:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - auth-service
      - musical-service

networks:
  backend:
    external: true
