// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: musical.proto

package musicalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_musical_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_musical_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_musical_proto_rawDescGZIP(), []int{0}
}

func (x *IDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_musical_proto protoreflect.FileDescriptor

const file_musical_proto_rawDesc = "" +
	"\n" +
	"\rmusical.proto\x12\amusical\x1a\valbum.proto\x1a\fartist.proto\x1a\n" +
	"like.proto\x1a\vtrack.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1b\n" +
	"\tIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x95\t\n" +
	"\x0eMusicalService\x120\n" +
	"\tGetArtist\x12\x12.musical.IDRequest\x1a\x0f.musical.Artist\x12H\n" +
	"\vListArtists\x12\x1b.musical.ListArtistsRequest\x1a\x1c.musical.ListArtistsResponse\x12:\n" +
	"\vCreateAlbum\x12\x1b.musical.CreateAlbumRequest\x1a\x0e.musical.Album\x12.\n" +
	"\bGetAlbum\x12\x12.musical.IDRequest\x1a\x0e.musical.Album\x12:\n" +
	"\vUpdateAlbum\x12\x1b.musical.UpdateAlbumRequest\x1a\x0e.musical.Album\x129\n" +
	"\vDeleteAlbum\x12\x12.musical.IDRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\n" +
	"ListAlbums\x12\x1a.musical.ListAlbumsRequest\x1a\x1b.musical.ListAlbumsResponse\x12:\n" +
	"\vCreateTrack\x12\x1b.musical.CreateTrackRequest\x1a\x0e.musical.Track\x12.\n" +
	"\bGetTrack\x12\x12.musical.IDRequest\x1a\x0e.musical.Track\x12:\n" +
	"\vUpdateTrack\x12\x1b.musical.UpdateTrackRequest\x1a\x0e.musical.Track\x129\n" +
	"\vDeleteTrack\x12\x12.musical.IDRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\n" +
	"ListTracks\x12\x1a.musical.ListTracksRequest\x1a\x1b.musical.ListTracksResponse\x12@\n" +
	"\n" +
	"LikeArtist\x12\x1a.musical.LikeArtistRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fUnlikeArtist\x12\x1c.musical.UnlikeArtistRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x0fGetLikedArtists\x12\x1f.musical.GetLikedArtistsRequest\x1a .musical.GetLikedArtistsResponse\x12>\n" +
	"\tLikeTrack\x12\x19.musical.LikeTrackRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\vUnlikeTrack\x12\x1b.musical.UnlikeTrackRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x0eGetLikedTracks\x12\x1e.musical.GetLikedTracksRequest\x1a\x1f.musical.GetLikedTracksResponseBCZAgithub.com/TeoPlow/online-music-service/src/musical/pkg/musicalpbb\x06proto3"

var (
	file_musical_proto_rawDescOnce sync.Once
	file_musical_proto_rawDescData []byte
)

func file_musical_proto_rawDescGZIP() []byte {
	file_musical_proto_rawDescOnce.Do(func() {
		file_musical_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_musical_proto_rawDesc), len(file_musical_proto_rawDesc)))
	})
	return file_musical_proto_rawDescData
}

var file_musical_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_musical_proto_goTypes = []any{
	(*IDRequest)(nil),               // 0: musical.IDRequest
	(*ListArtistsRequest)(nil),      // 1: musical.ListArtistsRequest
	(*CreateAlbumRequest)(nil),      // 2: musical.CreateAlbumRequest
	(*UpdateAlbumRequest)(nil),      // 3: musical.UpdateAlbumRequest
	(*ListAlbumsRequest)(nil),       // 4: musical.ListAlbumsRequest
	(*CreateTrackRequest)(nil),      // 5: musical.CreateTrackRequest
	(*UpdateTrackRequest)(nil),      // 6: musical.UpdateTrackRequest
	(*ListTracksRequest)(nil),       // 7: musical.ListTracksRequest
	(*LikeArtistRequest)(nil),       // 8: musical.LikeArtistRequest
	(*UnlikeArtistRequest)(nil),     // 9: musical.UnlikeArtistRequest
	(*GetLikedArtistsRequest)(nil),  // 10: musical.GetLikedArtistsRequest
	(*LikeTrackRequest)(nil),        // 11: musical.LikeTrackRequest
	(*UnlikeTrackRequest)(nil),      // 12: musical.UnlikeTrackRequest
	(*GetLikedTracksRequest)(nil),   // 13: musical.GetLikedTracksRequest
	(*Artist)(nil),                  // 14: musical.Artist
	(*ListArtistsResponse)(nil),     // 15: musical.ListArtistsResponse
	(*Album)(nil),                   // 16: musical.Album
	(*emptypb.Empty)(nil),           // 17: google.protobuf.Empty
	(*ListAlbumsResponse)(nil),      // 18: musical.ListAlbumsResponse
	(*Track)(nil),                   // 19: musical.Track
	(*ListTracksResponse)(nil),      // 20: musical.ListTracksResponse
	(*GetLikedArtistsResponse)(nil), // 21: musical.GetLikedArtistsResponse
	(*GetLikedTracksResponse)(nil),  // 22: musical.GetLikedTracksResponse
}
var file_musical_proto_depIdxs = []int32{
	0,  // 0: musical.MusicalService.GetArtist:input_type -> musical.IDRequest
	1,  // 1: musical.MusicalService.ListArtists:input_type -> musical.ListArtistsRequest
	2,  // 2: musical.MusicalService.CreateAlbum:input_type -> musical.CreateAlbumRequest
	0,  // 3: musical.MusicalService.GetAlbum:input_type -> musical.IDRequest
	3,  // 4: musical.MusicalService.UpdateAlbum:input_type -> musical.UpdateAlbumRequest
	0,  // 5: musical.MusicalService.DeleteAlbum:input_type -> musical.IDRequest
	4,  // 6: musical.MusicalService.ListAlbums:input_type -> musical.ListAlbumsRequest
	5,  // 7: musical.MusicalService.CreateTrack:input_type -> musical.CreateTrackRequest
	0,  // 8: musical.MusicalService.GetTrack:input_type -> musical.IDRequest
	6,  // 9: musical.MusicalService.UpdateTrack:input_type -> musical.UpdateTrackRequest
	0,  // 10: musical.MusicalService.DeleteTrack:input_type -> musical.IDRequest
	7,  // 11: musical.MusicalService.ListTracks:input_type -> musical.ListTracksRequest
	8,  // 12: musical.MusicalService.LikeArtist:input_type -> musical.LikeArtistRequest
	9,  // 13: musical.MusicalService.UnlikeArtist:input_type -> musical.UnlikeArtistRequest
	10, // 14: musical.MusicalService.GetLikedArtists:input_type -> musical.GetLikedArtistsRequest
	11, // 15: musical.MusicalService.LikeTrack:input_type -> musical.LikeTrackRequest
	12, // 16: musical.MusicalService.UnlikeTrack:input_type -> musical.UnlikeTrackRequest
	13, // 17: musical.MusicalService.GetLikedTracks:input_type -> musical.GetLikedTracksRequest
	14, // 18: musical.MusicalService.GetArtist:output_type -> musical.Artist
	15, // 19: musical.MusicalService.ListArtists:output_type -> musical.ListArtistsResponse
	16, // 20: musical.MusicalService.CreateAlbum:output_type -> musical.Album
	16, // 21: musical.MusicalService.GetAlbum:output_type -> musical.Album
	16, // 22: musical.MusicalService.UpdateAlbum:output_type -> musical.Album
	17, // 23: musical.MusicalService.DeleteAlbum:output_type -> google.protobuf.Empty
	18, // 24: musical.MusicalService.ListAlbums:output_type -> musical.ListAlbumsResponse
	19, // 25: musical.MusicalService.CreateTrack:output_type -> musical.Track
	19, // 26: musical.MusicalService.GetTrack:output_type -> musical.Track
	19, // 27: musical.MusicalService.UpdateTrack:output_type -> musical.Track
	17, // 28: musical.MusicalService.DeleteTrack:output_type -> google.protobuf.Empty
	20, // 29: musical.MusicalService.ListTracks:output_type -> musical.ListTracksResponse
	17, // 30: musical.MusicalService.LikeArtist:output_type -> google.protobuf.Empty
	17, // 31: musical.MusicalService.UnlikeArtist:output_type -> google.protobuf.Empty
	21, // 32: musical.MusicalService.GetLikedArtists:output_type -> musical.GetLikedArtistsResponse
	17, // 33: musical.MusicalService.LikeTrack:output_type -> google.protobuf.Empty
	17, // 34: musical.MusicalService.UnlikeTrack:output_type -> google.protobuf.Empty
	22, // 35: musical.MusicalService.GetLikedTracks:output_type -> musical.GetLikedTracksResponse
	18, // [18:36] is the sub-list for method output_type
	0,  // [0:18] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_musical_proto_init() }
func file_musical_proto_init() {
	if File_musical_proto != nil {
		return
	}
	file_album_proto_init()
	file_artist_proto_init()
	file_like_proto_init()
	file_track_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_musical_proto_rawDesc), len(file_musical_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_musical_proto_goTypes,
		DependencyIndexes: file_musical_proto_depIdxs,
		MessageInfos:      file_musical_proto_msgTypes,
	}.Build()
	File_musical_proto = out.File
	file_musical_proto_goTypes = nil
	file_musical_proto_depIdxs = nil
}
