dbconnection: postgresql://user:password@localhost:5432/music
grpc_port: :8000

log:
  level: info

minio:
  endpoint: "localhost:9000"
  access: "minioadmin"
  secret: "minioadmin123"
  ssl: false

kafka:
  brokers: ["localhost:9094"]
  consumer_group: "musical-consumer-group"
  version: 2.8.0
  auto_commit_interval: 1s
  retries: 5
