dbconnection: postgresql://user:password@postgres:5432/musical_db
grpc_port: :50052
redisurl: redis://redis:6379

log:
  level: info

minio:
  endpoint: "minio:9000"
  access: "minioadmin"
  secret: "minioadmin123"
  ssl: false

kafka:
  brokers: ["kafka:9092"]
  consumer_group: "musical-consumer-group"
  version: 2.8.0
  auto_commit_interval: 1s
  retries: 5
