dbconnection: postgresql://test:test@localhost:5432/test-musical

log:
  level: debug
  file: logs.json

minio:
  endpoint: "localhost:9000"
  access: "minioadmin"
  secret: "minioadmin123"
  ssl: false
