dbconnection: "postgresql://test:test@localhost:5432/test-musical?sslmode=disable"

log:
  level: debug
  file: logs.json

minio:
  endpoint: "localhost:9000"
  access: "minioadmin"
  secret: "minioadmin123"
  ssl: false

kafka:
  brokers: ["localhost:9094"]
  topics:
    artist_created: "artist.created"
    artist_updated: "artist.updated"
    artist_deleted: "artist.deleted"
  consumer_group: "test-consumer-group"
  version: "2.8.0"
  auto_commit_interval: 1s
  group_id: "test-group-id"