log:
  level: INFO
  save_to_file: False

kafka:
  bootstrap_servers: localhost:9092
  topics:
    - auth-users
    - music-artists
    - music-albums
    - music-tracks
    - music-liked-artists
    - music-liked-tracks

clickhouse:
  host: localhost
  port: 9000
  user: default
  password: "mysecurepassword"
  database: music_streaming