// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TeoPlow/online-music-service/src/musical/internal/domain (interfaces: TrackRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/TeoPlow/online-music-service/src/musical/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTrackRepo is a mock of TrackRepo interface.
type MockTrackRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTrackRepoMockRecorder
}

// MockTrackRepoMockRecorder is the mock recorder for MockTrackRepo.
type MockTrackRepoMockRecorder struct {
	mock *MockTrackRepo
}

// NewMockTrackRepo creates a new mock instance.
func NewMockTrackRepo(ctrl *gomock.Controller) *MockTrackRepo {
	mock := &MockTrackRepo{ctrl: ctrl}
	mock.recorder = &MockTrackRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackRepo) EXPECT() *MockTrackRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTrackRepo) Add(arg0 context.Context, arg1 models.Track) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockTrackRepoMockRecorder) Add(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTrackRepo)(nil).Add), arg0, arg1)
}

// Delete mocks base method.
func (m *MockTrackRepo) Delete(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTrackRepoMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTrackRepo)(nil).Delete), arg0, arg1)
}

// FindCopy mocks base method.
func (m *MockTrackRepo) FindCopy(arg0 context.Context, arg1 models.Track) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCopy", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCopy indicates an expected call of FindCopy.
func (mr *MockTrackRepoMockRecorder) FindCopy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCopy", reflect.TypeOf((*MockTrackRepo)(nil).FindCopy), arg0, arg1)
}

// GetByFilter mocks base method.
func (m *MockTrackRepo) GetByFilter(arg0 context.Context, arg1, arg2 int, arg3, arg4 *string, arg5 *uuid.UUID) ([]models.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFilter", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]models.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFilter indicates an expected call of GetByFilter.
func (mr *MockTrackRepoMockRecorder) GetByFilter(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFilter", reflect.TypeOf((*MockTrackRepo)(nil).GetByFilter), arg0, arg1, arg2, arg3, arg4, arg5)
}

// GetByID mocks base method.
func (m *MockTrackRepo) GetByID(arg0 context.Context, arg1 uuid.UUID) (models.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(models.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTrackRepoMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTrackRepo)(nil).GetByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockTrackRepo) Update(arg0 context.Context, arg1 models.Track) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTrackRepoMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTrackRepo)(nil).Update), arg0, arg1)
}
