env: default

db_url: postgres://user:password@postgres:5432/auth_db?sslmode=disable
  
access_token_ttl: 1h
refresh_token_ttl: 24h

grpc_server:
  port: 50051
  timeout: 10h

jwt_secret: "secret"

redis:
  host: redis
  port: 6379
  password: ""
  db: 0
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s


kafka:
  brokers:
    - kafka:9092
  tls:
    enable: false
  topics:
    user_created: user.created
    artist_created: artist.created
  retries: 5
  version: "3.2.3"
  retry_backoff: 100ms
  flush_frequency: 200ms
  compression: snappy
  client_id: auth

outbox:
  batch_size: 100
  poll_interval: 2s